### ISSUE TITLE
关于文件名称存在windows不支持的特殊字符

### ISSUE THREAD

**Issue by Zacharia2** [L-M-Sherlock/thoughts-memo-translation#1]
- 此文件含有英文状态下的问号 `andy\note\spaced-repetition\To what extent does spaced repetition memory system practice constitute deliberate practice?.md` 
- 此文件含有英文状态下的问号 `andy\note\To what extent do review sessions offer prompt-writing feedback?.md`
- 此文件含有英文状态下的冒号 `masterhowtolearn\Why I No Longer Tell My Friends about Anki:SuperMemo.md`
- 此文件含有英文状态下的问号 `rice\learning\What counts as good motivation?.md`

- 此文件含有英文状态下的问号 `rice\learning\What makes a word explanation good?.md`
- 此文件含有英文状态下的问号 `rice\notes\Can spaced repetition interfere with internal sense of relevance?.md`
- 此文件含有英文状态下的问号 `rice\SRS\Can spaced repetition interfere with internal sense of relevance?.md`

另外此仓库中：https://github.com/L-M-Sherlock/supermemo.guru-cn

- 此文件含有英文状态下的问号`ToolsForThought\spaced-repetition\To what extent does spaced repetition memory system practice constitute deliberate practice?.md`
- 此文件含有英文状态下的问号`ToolsForThought\spaced-repetition\To what extent do review sessions offer prompt-writing feedback?.md`
- 此文件含有英文状态下的冒号`MasterHowToLearn\Why I No Longer Tell My Friends about Anki:SuperMemo.md`

文件名不能包含下列任何字符：` ?`   `“`   `”`  `/`    `\`   `<`   `>`   `*`   `|`  `:` 

解决方案，改成中文状态下的字符即可。例如英文问号`?`改成中文问号`？`

**Comment by Zacharia2** [comment]
我不知道他是否重要，如果不重要，请关闭它。

**Comment by L-M-Sherlock** [comment]
这些译文都是我用脚本拼接的，并且没有进一步校对，不打算在 GitHub 上进行调整。

**Comment by Zacharia2** [comment]
辛苦了，叶哥，okk
