### ISSUE TITLE
格式错误

### ISSUE THREAD

**Issue by dongrentianyu** [L-M-Sherlock/thoughts-memo-translation#2]
Why the Best Teachers Don't Give Tests

![image](https://github.com/L-M-Sherlock/thoughts-memo-translation/assets/109711900/dd3e18a0-7e5f-4e3f-9661-0ab4c9e6be42)

**Comment by dongrentianyu** [comment]
原文标题前可以加上“原文：”，这样就和andy笔记保持一致了，然后就可以搜索到了。因为没有“原文：”就匹配不出来

**Comment by L-M-Sherlock** [comment]
这篇还未发表，译者不一定会遵守格式。还需要校对。

**Comment by dongrentianyu** [comment]
哦哦，明白了
